# bank-security's application.yml file
spring:
  config:
    import: optional:configserver:http://localhost:8888
    location: classpath:/configurations/bank-common.yml
  application:
    name: bank-security
  main:
    web-application-type: reactive

logging:
  level:
    root: info
    org.springframework.web.reactive.function.client: info
    reactor.netty.http.client: info
    org.springframework.r2dbc: info
    org.springframework.data.r2dbc.core: info
    io.r2dbc.postgresql.QUERY: info
    org.springframework.web: info
    am.banking.system.security: info
    am.banking.system.user: info
    org.springframework.web.client: info
    org.springframework.web.reactive: info
    org.springframework.security: debug
    org.springframework.security.web: info
    org.springframework.web.reactive.function.client.ExchangeFunctions: trace
