# bank-security's application.yml file
spring:
  config:
    import: optional:configserver:http://localhost:8888
    location: classpath:/configurations/bank-common.yml
  application:
    name: bank-security
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.r2dbc: debug