# bank-security's application.yml file
spring:
  config:
    import: optional:configserver:http://localhost:8888
    additional-location: classpath:/configurations/bank-common.yml
  application:
    name: bank-security
  main:
    web-application-type: reactive

logging:
  level:
    web: info
    root: info
    sql: debug
    org:
      springframework:
        web:
          client: info
          reactive:
            function:
              client:
                ExchangeFunction: trace
              _: info
            _: info
          _: info
        _: info
        security:
          core: debug
          web: debug
        data:
          r2dbc:
            core: debug
          _: debug
        r2dbc: debug
    reactor:
      netty:
        http:
          server: debug
          client: debug
    io:
      r2dbc:
        postgresql:
          QUERY: debug
        spi: debug
    am:
      banking:
        system:
          user: debug
          security: debug
          notification: debug