# bank-user.yml from configuration-server service
server:
  port: 8090
  ssl:
    enabled: false

webclient:
  tls:
    url: http://localhost:8989
    key-store: /Users/artyom_aroyan/.keys/.bankapp/REST/security-keystore.p12
    key-store-password: ${SECURITY_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    trust-store: /Users/artyom_aroyan/.keys/.bankapp/REST/security-truststore.p12
    trust-store-password: ${SECURITY_TRUSTSTORE_PASSWORD}
    trust-store-type: PKCS12
    client-auth: need

internal:
  system:
    secret: ${X_INTERNAL_SECRET}

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/user_db
    username: user_owner
    password: user_owner

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/user_db
    user: user_owner
    password: user_owner
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver
    schemas: usr
    default-schema: usr

resilience4j:
  retry:
    instances:
      securityService:
        max-attempts: 3
        wait-duration:
          seconds: 1

      notificationService:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.io.IOException
        ignore-exceptions: []
        fail-after-max-attempts: true

  circuitbreaker:
    instances:
      securityService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-type: count_based
        sliding-window-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 10

      notificationService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10 # look at last 10 calls
        minimum-number-of-calls: 5 # only start calculating after 5 calls
        failure-rate-threshold: 50 # if 50% of calls fail -> open the circuit
        slow-call-rate-threshold: 50 # if 50% slow calls (timeout) -> open the circuit
        slow-call-duration-threshold: 2s # anything longer than 2s is considered slow
        wait-duration-in-open-state: 15s # after 15s circuit will move to half-open
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.io.IOException
        ignore-exceptions: []

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

logging:
  level:
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.cloud: info