# bank-notification.yml from configuration-server service
server:
  port: 8040
  ssl:
    enabled: false

internal:
  system:
    secret: ${X_INTERNAL_SECRET}

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/notification_db
    username: notification_owner
    password: notify_owner

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/notification_db
    user: notification_owner
    password: notify_owner
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver
    schemas: notification
    default-schema: notification

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        metadata.max.age.ms: 100
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:

  mail:
    host: smtp.gmail.com
    port: 587
    username: artyomaroyan.j@gmail.com
    password: bzcp kbmf haum wiog
    protocol: smtp
    auth: true
    enable: true
    require: true