# bank-notification.yml from configuration-server service
server:
  port: 8040
  ssl:
    enabled: false

webclient:
  tls:
    url: http://localhost:8989
    key-store: /Users/artyom_aroyan/.keys/.bankapp/REST/security-keystore.p12
    key-store-password: ${SECURITY_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    trust-store: /Users/artyom_aroyan/.keys/.bankapp/REST/security-truststore.p12
    trust-store-password: ${SECURITY_TRUSTSTORE_PASSWORD}
    trust-store-type: PKCS12

internal:
  system:
    secret: ${X_INTERNAL_SECRET}

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/notification_db
    username: notification_owner
    password: notify_owner

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/notification_db
    user: notification_owner
    password: notify_owner
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver
    schemas: notification
    default-schema: notification

  kafka:
    consumer:
      bootstrap-servers: http://localhost:9092
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        metadata.max.age.ms: 100
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:

  mail:
    host: localhost
    port: 1025
    username: admin
    password: secret
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000