server:
  port: 8181
  ssl:
    enabled: false

webclient:
  tls:
    url: http://localhost:8989
    key-store: /Users/artyom_aroyan/.keys/.bankapp/REST/security-keystore.p12
    key-store-password: ${SECURITY_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    trust-store: /Users/artyom_aroyan/.keys/.bankapp/REST/security-truststore.p12
    trust-store-password: ${SECURITY_TRUSTSTORE_PASSWORD}
    trust-store-type: PKCS12
    client-auth: need

internal:
  system:
    secret: ${X_INTERNAL_SECRET}

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/account_db
    username: account_owner
    password: account_owner

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/account_db
    user: account_owner
    password: account_owner
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver
    default-schema: account