server:
  port: 8181
  ssl:
    enabled: false

internal:
  system:
    secret: ${X_INTERNAL_SECRET}

outbox:
  publish-interval: 2000

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/account_db
    username: account_owner
    password: account_owner

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/account_db
    user: account_owner
    password: account_owner
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver
    default-schema: account

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer