# bank-user.yml from configuration-server service
server:
  port: 8090

security:
  service:
    url: https://localhost:8090

webclient:
  ssl:
    keyStorePath: /Users/artyom_aroyan/.keys/.bankapp/REST/user-keystore.p12
    keyStorePassword: ${USER_KEYSTORE_PASSWORD}
    keyStoreType: PKCS12
    trustStorePath: /Users/artyom_aroyan/.keys/.bankapp/REST/user-truststore.p12
    trustStorePassword: ${USER_TRUSTSTORE_PASSWORD}
    trustStoreType: PKCS12
    clientAuth: need

spring:
  data:
    mongodb:
      username: admin
      password: secret
      host: localhost
      port: 27017
      database: user
      authentication-database: admin