server:
  port: 8040

notification:
  tls:
    base-url: https://localhost:8040

spring:
  data:
    mongodb:
      username: admin
      password: secret
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin

#  kafka:
#    consumer:
#      bootstrap-servers: ms_kafka:9092
#      group-id: notification-service-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: '*'
#        spring.json.type.mapping:

  mail:
    host: localhost
    port: 1025
    username: admin
    password: secret
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

logging:
  level:
    org.springframework.kafka: debug