server:
  port: 8181
  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:postgres://localhost:5432/account_db
    username: account_owner
    password: account_owner
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true