create table if not exists account_db.account.account(
    id integer unique not null generated by default as identity primary key ,
    account_owner_id integer unique not null ,
    account_number varchar(16) unique not null ,
    account_owner_username varchar(30) not null ,
    account_owner_full_name varchar(80) not null ,
    account_owner_email varchar(70) not null ,
    balance bigint not null ,
    account_type varchar(30) not null
);