# application.yml file in bank-user service
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: bank-user

  r2dbc:
    properties:
      show-sql: true

logging:
  level:
    root: info
    web: info
    sql: debug
    org:
      springframework:
        web:
          client: info
          reactive:
            function:
              client:
                ExchangeFunction: trace
              _: info
            _: info
          _: info
        _: info
        security:
          core: debug
          web: debug
        data:
          r2dbc:
            core: debug
          _: debug
        r2dbc: info
    reactor:
      netty:
        http:
          server: info
          client: info
    io:
      r2dbc:
        postgresql:
          QUERY: debug
        spi: debug
    am:
      banking:
        system:
          user: info
          security: info