# application.yml file in bank-user service
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: bank-user

logging:
  level:
    org.springframework.r2dbc: info
    org.springframework.web: info
    am.banking.system.security: info
    am.banking.system.user: info
    org.springframework.web.client: info
    org.springframework.web.reactive: info
    org.springframework.security: info
    org.springframework.security.web: info