create table if not exists notification_db.notification.notification(
    id integer unique not null primary key generated by default as identity ,
    email_type varchar(20) not null ,
    notification_date timestamp not null ,
    email_verification varchar(500),
    password_reset varchar(500),
    welcome_email varchar(500)
);