create table if not exists notification_db.notification.notification(
    id integer unique not null primary key generated by default as identity ,
    created_at timestamp not null default current_timestamp ,
    email_type varchar(20) not null ,
    notification_date timestamp not null ,
    recipient_email varchar(100),
    username varchar(30),
    verification_link varchar(800)
);