create table if not exists security.user_token(
    id integer unique not null primary key generated by default as identity,
    user_id text not null ,
    created_at timestamp not null default current_timestamp ,
    expires_at timestamp not null ,
    token varchar(800) not null ,
    token_state varchar(30) not null ,
    token_purpose varchar(30) not null
);

create or replace function prevent_id_update() returns trigger as $$
    begin
        if new.id <> old.id then
            raise exception 'ID is not updatable';
        end if;
        return new;
end;
$$ language plpgsql;
end;

create trigger trg_prevent_id_update
    before update on security.user_token
    for each row
    execute function prevent_id_update();