package am.banking.system.common.enums;

/**
 * Author: Artyom Aroyan
 * Date: 13.04.25
 * Time: 23:51:21
 */
public enum PermissionEnum {
    // AUTHENTICATION
    VIEW_PUBLIC_INFO,
    REGISTER_ACCOUNT,
    LOGIN,
    LOGOUT,

    // USER PROFILE
    VIEW_OWN_PROFILE,
    UPDATE_OWN_PROFILE,
    VIEW_ALL_USERS,
    UPDATE_ANY_USER,
    DELETE_USER,

    // ACCOUNTS
    OPEN_ACCOUNT,
    VIEW_OWN_ACCOUNTS,
    VIEW_ALL_ACCOUNTS,
    FREEZE_ACCOUNT,
    UNFREEZE_ACCOUNT,
    CLOSE_ACCOUNT,

    // TRANSACTIONS
    MAKE_TRANSACTION,
    VIEW_OWN_TRANSACTIONS,
    VIEW_ALL_TRANSACTIONS,
    APPROVE_LARGE_TRANSACTION,
    ROLLBACK_TRANSACTION,

    // ROLES & PERMISSIONS
    VIEW_ROLES_AND_PERMISSIONS,
    ASSIGN_ROLES,
    MANAGE_PERMISSIONS,

    // NOTIFICATIONS & AUDIT
    VIEW_OWN_NOTIFICATIONS,
    VIEW_AUDIT_LOGS,

    // SYSTEM
    GENERATE_SYSTEM_TOKEN
}