# bank-notification's application.yml file
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: bank-notification

  kafka:
    consumer:
      bootstrap-servers: ms_kafka:9092
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: