create table if not exists user_db.usr.usr(
    id integer unique not null primary key generated by default as identity ,
    created_at timestamp not null default CURRENT_TIMESTAMP,
    updated_at timestamp not null default CURRENT_TIMESTAMP,
    username varchar(30) not null unique ,
    first_name varchar(50) not null ,
    last_name varchar(50) not null ,
    email varchar(70) not null unique ,
    password varchar(800) not null ,
    phone varchar(15) not null unique ,
    age integer not null ,
    account_state varchar(20) not null
);