create table if not exists usr.role(
    id integer unique not null primary key generated by default as identity ,
    created_at timestamp not null default CURRENT_TIMESTAMP,
    updated_at timestamp not null default CURRENT_TIMESTAMP,
    role_name varchar(30) not null unique
);