create table if not exists usr.permission(
    id integer unique not null primary key generated by default as identity ,
    created_at timestamp not null default CURRENT_TIMESTAMP,
    updated_at timestamp not null default CURRENT_TIMESTAMP,
    permission_name varchar(50) not null unique
);