create table if not exists user_db.usr.permission(
    id integer unique not null primary key generated by default as identity ,
    created_at timestamp not null default CURRENT_TIMESTAMP,
    updated_at timestamp not null default CURRENT_TIMESTAMP,
    permission_enum varchar(50) not null unique
);