# application.yml file in configuration-server service
server:
  port: 8888
  ssl:
    enabled: false

spring:
  application:
    name: configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

---
spring:
  config:
    activate:
      on-profile: native