# application.yml file in configuration-server service
server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: configuration-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations